# Generated by Django 6.0.7 on 2026-07-27 00:35

import django.db.models.deletion
import things.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Thing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        default=models.AutoField(primary_key=True, serialize=False),
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(blank=True, default=None, max_length=100)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("assigned_date", models.DateField(blank=True, null=True)),
                (
                    "last_assigned_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("missing_since", models.DateField(blank=True, null=True)),
                ("damaged_since", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=things.models.get_default_category,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="things.category",
                    ),
                ),
            ],
        ),
    ]
