# Generated by Django 6.0.7 on 2026-07-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                blank=True, default="Unnamed Category", max_length=100, unique=True
            ),
        ),
    ]
