# Generated by Django 6.0.7 on 2026-07-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
