# Generated by Django 6.0.7 on 2026-07-27 04:20

import django.db.models.deletion
import things.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0003_alter_thing_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="damaged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thing",
            name="missing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thing",
            name="returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="thing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=things.models.get_default_category,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="things.category",
            ),
        ),
    ]
