# Generated by Django 6.0.7 on 2026-07-27 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0004_thing_damaged_thing_missing_thing_returned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="things.category",
            ),
        ),
    ]
