# Generated by Django 6.0.7 on 2026-07-27 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0005_alter_thing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="things.category",
            ),
        ),
    ]
