# Generated by Django 6.0.7 on 2026-07-27 04:32

import django.db.models.deletion
import things.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0006_alter_thing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=things.models.get_default_category,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="things.category",
            ),
        ),
    ]
