# Generated by Django 6.0.7 on 2026-07-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0007_alter_thing_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thing",
            old_name="damaged_since",
            new_name="damaged_date",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="missing_since",
            new_name="missing_date",
        ),
    ]
