# Generated by Django 6.0.7 on 2026-07-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0008_rename_damaged_since_thing_damaged_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thing",
            old_name="name",
            new_name="description",
        ),
    ]
