# Generated by Django 6.0.7 on 2026-07-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0009_rename_name_thing_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thing",
            name="missing",
        ),
        migrations.RemoveField(
            model_name="thing",
            name="returned",
        ),
        migrations.AddField(
            model_name="thing",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("assigned", "Assigned"),
                    ("missing", "Missing"),
                ],
                default="available",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="thing",
            name="damaged",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
