# Generated by Django 6.0.7 on 2026-07-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0010_remove_thing_missing_remove_thing_returned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="fixed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
