# Generated by Django 6.0.7 on 2026-07-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0011_thing_fixed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="assigned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thing",
            name="damaged_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thing",
            name="fixed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thing",
            name="missing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thing",
            name="returned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
