# Generated by Django 6.0.7 on 2026-07-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0012_alter_thing_assigned_date_alter_thing_damaged_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="assigned_to",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
