# Generated by Django 6.0.7 on 2026-07-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0013_alter_thing_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("assigned", "Assigned"),
                    ("missing", "Missing"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
