# Generated by Django 6.0.7 on 2026-08-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0014_alter_thing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
