# Generated by Django 6.0.7 on 2026-08-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0015_alter_thing_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="assigned_to",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="thing",
            name="last_assigned_to",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="thing",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="thing",
            name="size",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
